index.md
Preview here https://runcom.github.io/cri-o.io/
the old one was the integration with openshift but we're focused on Kube first (eheh)
The new asciinema is a Multi Node/Multi OS demo
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> better asciinema

_layouts/default.html
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
=> Enable google analytics

index.md
First of a few dependent PRs to make the content more compelling and clear.
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
=> refactor content

_sass/jekyll-theme-cayman.scss, index.md
@jtligon this should be it for now.
=> UI bugfixs

_sass/jekyll-theme-cayman.scss
Fixes #13 
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
=> Fix mobile rendering issues

_layouts/default.html, _layouts/redirectblog.html, _sass/jekyll-theme-cayman.scss, blog.md
- redirect /blog to medium site
- add "Visit blog" link
=> Link to/from blog

index.md
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> index.md: fixups for use it and repos

index.md
@rhatdan please merge this.
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> index.md: add contribute

index.md
openSUSE's doing a lot with CRI-O, it would be nice to have those offerings reflected on the CRI-O website.
More than happy to rework this in response to any feedback, I consider this PR a conversation starter and I'm not arrogant enough to think I have gotten the wording right first time ;)
=> Add openSUSE info

index.md
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> fixups to RHEL stuff

index.md
=> Updated Kube Slack channel

index.md
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
Title says it all.
=> Add F28 and F29 to dists

index.md
Clear is dead, long live Kata Containers!
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> index: s/Clear/kata!

index.md
Fix an out of date link with an updated tutorial on setting up CRI-O with kubeadm
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> Update kubeadm 'Try Now' field

index.md
Signed-off-by: Michael Shen <mishen@umich.edu>
=> Fix typo, crio-o to cri-o

index.md
now that conmon is moved out of cri-o
Signed-off-by: Peter Hunt <pehunt@redhat.com>
=> fix conmon link

index.md
- recommend users to list versions available before installation
- update installation version
Reference: https://github.com/cri-o/cri-o/issues/2713
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
=> fedora: update documentation about CRI-O installation

index.md
Signed-off-by: Peter Hunt <pehunt@redhat.com>
```release-note
none
```
=> update installation instructions

_includes/cncf.html
@haircommander ptal
```release-note
Add license info and set graduated status
```
=> Add license info and graduated status

index.md
Refers to https://github.com/cri-o/cri-o/issues/8353
=> Sync install docs with packaging repo
